// flow-typed signature: 3902cdd17ecc2ea88da40dcfe43f304c
// flow-typed version: <<STUB>>/reselect-map_v^1.0.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reselect-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reselect-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reselect-map/lib/index' {
  declare module.exports: any;
}

declare module 'reselect-map/lib/memoize' {
  declare module.exports: any;
}

declare module 'reselect-map/src/index' {
  declare module.exports: any;
}

declare module 'reselect-map/src/memoize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reselect-map/lib/index.js' {
  declare module.exports: $Exports<'reselect-map/lib/index'>;
}
declare module 'reselect-map/lib/memoize.js' {
  declare module.exports: $Exports<'reselect-map/lib/memoize'>;
}
declare module 'reselect-map/src/index.js' {
  declare module.exports: $Exports<'reselect-map/src/index'>;
}
declare module 'reselect-map/src/memoize.js' {
  declare module.exports: $Exports<'reselect-map/src/memoize'>;
}
